-- No nutrition data is in use. This deliberately replaces the catalog-based item schema.
drop table meal_foods;
drop table foods;

create table meal_foods (
    id bigint generated by default as identity primary key,
    meal_id bigint not null references meals(id) on delete cascade,
    food_name varchar(100) not null,
    calories numeric(8, 2) not null check (calories >= 0),
    carbohydrate_grams numeric(8, 2) check (carbohydrate_grams >= 0),
    protein_grams numeric(8, 2) check (protein_grams >= 0),
    fat_grams numeric(8, 2) check (fat_grams >= 0),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);
create index idx_meal_foods_meal on meal_foods (meal_id, created_at);

alter table ai_messages add column message_kind varchar(20) not null default 'TEXT';
alter table ai_messages add column food_photo_result text;
alter table ai_request_logs add column request_kind varchar(20) not null default 'TEXT';
