create table exercises (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    name varchar(100) not null,
    category varchar(50),
    created_at timestamp with time zone not null,
    constraint uk_exercise_user_name unique (user_id, name)
);

create table workouts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    workout_date date not null,
    status varchar(20) not null,
    memo varchar(500),
    started_at timestamp with time zone not null,
    completed_at timestamp with time zone
);

create table workout_exercises (
    id bigint generated by default as identity primary key,
    workout_id bigint not null references workouts(id) on delete cascade,
    exercise_id bigint not null references exercises(id),
    order_index integer not null,
    memo varchar(500)
);

create table workout_sets (
    id bigint generated by default as identity primary key,
    workout_exercise_id bigint not null references workout_exercises(id) on delete cascade,
    set_number integer not null,
    weight_kg numeric(7, 2) not null,
    reps integer not null,
    duration_seconds integer,
    completed boolean not null
);

create index idx_workouts_user_date
    on workouts (user_id, workout_date desc);

create index idx_workouts_user_status_completed
    on workouts (user_id, status, completed_at desc);

create index idx_workout_exercises_exercise
    on workout_exercises (exercise_id);
