create table routines (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    name varchar(100) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_routine_user_name unique (user_id, name)
);

create table routine_exercises (
    id bigint generated by default as identity primary key,
    routine_id bigint not null references routines(id) on delete cascade,
    exercise_id bigint not null references exercises(id),
    order_index integer not null
);

create index idx_routines_user_updated
    on routines (user_id, updated_at desc);

create index idx_routine_exercises_routine_order
    on routine_exercises (routine_id, order_index);
