create table custom_exercises (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    name varchar(100) not null,
    category varchar(30) not null,
    created_at timestamp with time zone not null,
    constraint uk_custom_exercise_user_name unique (user_id, name)
);

insert into custom_exercises (id, user_id, name, category, created_at)
select id, user_id, name, coalesce(category, 'CHEST'), created_at
from exercises;

select setval(
    pg_get_serial_sequence('custom_exercises', 'id'),
    coalesce((select max(id) from custom_exercises), 1),
    exists(select 1 from custom_exercises)
);

create table workout_exercises_v3 (
    id bigint generated by default as identity primary key,
    workout_id bigint not null references workouts(id) on delete cascade,
    exercise_type varchar(20) not null,
    exercise_id bigint not null,
    exercise_name varchar(100) not null,
    category varchar(30) not null,
    order_index integer not null,
    memo varchar(500)
);

insert into workout_exercises_v3 (
    id, workout_id, exercise_type, exercise_id,
    exercise_name, category, order_index, memo
)
select
    we.id, we.workout_id, 'CUSTOM', we.exercise_id,
    ce.name, ce.category, we.order_index, we.memo
from workout_exercises we
join custom_exercises ce on ce.id = we.exercise_id;

select setval(
    pg_get_serial_sequence('workout_exercises_v3', 'id'),
    coalesce((select max(id) from workout_exercises_v3), 1),
    exists(select 1 from workout_exercises_v3)
);

create table workout_sets_v3 (
    id bigint generated by default as identity primary key,
    workout_exercise_id bigint not null references workout_exercises_v3(id) on delete cascade,
    set_number integer not null,
    weight_kg numeric(7, 2) not null,
    reps integer not null,
    duration_seconds integer,
    completed boolean not null
);

insert into workout_sets_v3 (
    id, workout_exercise_id, set_number,
    weight_kg, reps, duration_seconds, completed
)
select
    id, workout_exercise_id, set_number,
    weight_kg, reps, duration_seconds, completed
from workout_sets;

select setval(
    pg_get_serial_sequence('workout_sets_v3', 'id'),
    coalesce((select max(id) from workout_sets_v3), 1),
    exists(select 1 from workout_sets_v3)
);

create table routine_exercises_v3 (
    id bigint generated by default as identity primary key,
    routine_id bigint not null references routines(id) on delete cascade,
    exercise_type varchar(20) not null,
    exercise_id bigint not null,
    exercise_name varchar(100) not null,
    category varchar(30) not null,
    order_index integer not null
);

insert into routine_exercises_v3 (
    id, routine_id, exercise_type, exercise_id,
    exercise_name, category, order_index
)
select
    re.id, re.routine_id, 'CUSTOM', re.exercise_id,
    ce.name, ce.category, re.order_index
from routine_exercises re
join custom_exercises ce on ce.id = re.exercise_id;

select setval(
    pg_get_serial_sequence('routine_exercises_v3', 'id'),
    coalesce((select max(id) from routine_exercises_v3), 1),
    exists(select 1 from routine_exercises_v3)
);

drop table workout_sets;
drop table workout_exercises;
drop table routine_exercises;
drop table exercises;

alter table workout_exercises_v3 rename to workout_exercises;
alter table workout_sets_v3 rename to workout_sets;
alter table routine_exercises_v3 rename to routine_exercises;

create table exercises (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    category varchar(30) not null,
    sort_order integer not null,
    constraint uk_exercise_name unique (name)
);

create index idx_workout_exercises_reference
    on workout_exercises (exercise_type, exercise_id);

create index idx_routine_exercises_routine_order
    on routine_exercises (routine_id, order_index);

create index idx_custom_exercises_user_category
    on custom_exercises (user_id, category, name);

insert into exercises (name, category, sort_order) values
('벤치프레스', 'CHEST', 10),
('인클라인 벤치프레스', 'CHEST', 20),
('덤벨 벤치프레스', 'CHEST', 30),
('체스트 프레스', 'CHEST', 40),
('케이블 플라이', 'CHEST', 50),
('펙덱 플라이', 'CHEST', 60),
('딥스', 'CHEST', 70),
('오버헤드 프레스', 'SHOULDER', 10),
('덤벨 숄더 프레스', 'SHOULDER', 20),
('사이드 레터럴 레이즈', 'SHOULDER', 30),
('프론트 레이즈', 'SHOULDER', 40),
('리어 델트 플라이', 'SHOULDER', 50),
('페이스 풀', 'SHOULDER', 60),
('랫풀다운', 'BACK', 10),
('풀업', 'BACK', 20),
('바벨 로우', 'BACK', 30),
('시티드 케이블 로우', 'BACK', 40),
('원암 덤벨 로우', 'BACK', 50),
('티바 로우', 'BACK', 60),
('데드리프트', 'BACK', 70),
('바벨 컬', 'ARM', 10),
('덤벨 컬', 'ARM', 20),
('해머 컬', 'ARM', 30),
('케이블 푸시다운', 'ARM', 40),
('스컬 크러셔', 'ARM', 50),
('오버헤드 트라이셉스 익스텐션', 'ARM', 60),
('크런치', 'ABS', 10),
('레그 레이즈', 'ABS', 20),
('행잉 레그 레이즈', 'ABS', 30),
('케이블 크런치', 'ABS', 40),
('플랭크', 'ABS', 50),
('앱 롤아웃', 'ABS', 60),
('스쿼트', 'LEGS', 10),
('레그 프레스', 'LEGS', 20),
('런지', 'LEGS', 30),
('레그 익스텐션', 'LEGS', 40),
('레그 컬', 'LEGS', 50),
('루마니안 데드리프트', 'LEGS', 60),
('힙 쓰러스트', 'LEGS', 70),
('카프 레이즈', 'LEGS', 80);
