create table body_records (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    weight_kg numeric(5, 2) not null,
    body_fat_percentage numeric(5, 2) not null,
    skeletal_muscle_kg numeric(5, 2) not null,
    measured_at timestamp with time zone not null,
    memo varchar(500),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint ck_body_record_weight_positive check (weight_kg > 0),
    constraint ck_body_record_body_fat_range
        check (body_fat_percentage >= 0 and body_fat_percentage <= 100),
    constraint ck_body_record_skeletal_muscle_positive
        check (skeletal_muscle_kg > 0)
);

create index idx_body_records_user_measured_at
    on body_records (user_id, measured_at desc);
