create table foods (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    name varchar(100) not null,
    serving_amount numeric(8, 2) not null,
    serving_unit varchar(20) not null,
    calories numeric(8, 2) not null,
    carbohydrate_grams numeric(8, 2) not null,
    protein_grams numeric(8, 2) not null,
    fat_grams numeric(8, 2) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_foods_user_name unique (user_id, name),
    constraint ck_foods_serving_amount_positive check (serving_amount > 0),
    constraint ck_foods_calories_non_negative check (calories >= 0),
    constraint ck_foods_carbohydrate_non_negative check (carbohydrate_grams >= 0),
    constraint ck_foods_protein_non_negative check (protein_grams >= 0),
    constraint ck_foods_fat_non_negative check (fat_grams >= 0)
);

create index idx_foods_user_name
    on foods (user_id, name);

create table meals (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    meal_date date not null,
    meal_type varchar(20) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_meals_user_date_type unique (user_id, meal_date, meal_type)
);

create index idx_meals_user_date
    on meals (user_id, meal_date desc);

create table meal_foods (
    id bigint generated by default as identity primary key,
    meal_id bigint not null references meals(id) on delete cascade,
    source_food_id bigint not null,
    food_name varchar(100) not null,
    serving_amount numeric(8, 2) not null,
    serving_unit varchar(20) not null,
    calories_per_serving numeric(8, 2) not null,
    carbohydrate_grams_per_serving numeric(8, 2) not null,
    protein_grams_per_serving numeric(8, 2) not null,
    fat_grams_per_serving numeric(8, 2) not null,
    servings numeric(6, 2) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint ck_meal_food_servings_range
        check (servings > 0 and servings <= 100),
    constraint ck_meal_food_calories_non_negative
        check (calories_per_serving >= 0),
    constraint ck_meal_food_carbohydrate_non_negative
        check (carbohydrate_grams_per_serving >= 0),
    constraint ck_meal_food_protein_non_negative
        check (protein_grams_per_serving >= 0),
    constraint ck_meal_food_fat_non_negative
        check (fat_grams_per_serving >= 0)
);

create index idx_meal_foods_meal
    on meal_foods (meal_id, created_at);

create index idx_meal_foods_source_food
    on meal_foods (source_food_id);

create table nutrition_goals (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    calories numeric(8, 2) not null,
    carbohydrate_grams numeric(8, 2) not null,
    protein_grams numeric(8, 2) not null,
    fat_grams numeric(8, 2) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_nutrition_goals_user unique (user_id),
    constraint ck_nutrition_goal_calories_positive check (calories > 0),
    constraint ck_nutrition_goal_carbohydrate_non_negative
        check (carbohydrate_grams >= 0),
    constraint ck_nutrition_goal_protein_non_negative
        check (protein_grams >= 0),
    constraint ck_nutrition_goal_fat_non_negative
        check (fat_grams >= 0)
);
